name: 'dbt_cliniq'
version: '1.0.0'
config-version: 2

profile: 'dbt_cliniq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_cliniq:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

vars:
  # Default lookback window (days) for gap detection
  gap_lookback_days: 365
